feat(core): Add facet/collection channel methods (#1725)
vendure-ecommerce/vendure pull request #1740
Opened 2022-08-24 17:07 UTC by Izayda

Add assignFacetsToChannel, removeFacetsFromChannel, assignCollectionsToChannel, removeCollectionsFromChannel methods (#1725)

2022-09-14 15:14 UTC, michaelbromley commented
Adding some comments from Slack:

---

Izayda: What actions should be triggered in search plugin? Full reindex?

Michael: Interesting question. With Facets, I think we need to consider what happens when we remove a facet from Channel A, but it is still assigned to a Product in Channel A. I just briefly looked at the code and I think maybe we're already missing something here. I need to spend more time on this one.

Izayda: I remember, that we can’t “reverse engineer” what products and variants will be affected by changing some collection/facet, cause custom mapping can be implemented through plugin. So, yeah, it is interesting question 🙂 

---

Current status: I intend to get this into v1.8 but need to resolve the issues raised above.

2022-09-14 15:39 UTC, Izayda commented
So, what can i do here along with the resolving merge conflict?

2022-09-15 07:02 UTC, michaelbromley commented
OK so how about we handle the above case like this:

- On removing a Facet from a Channel
- we check to see if any Products or ProductVariants in that channel have that Facet assigned
- If yes, we can either (in order of complexity):
    1. Fail with an error
    2. Automatically remove that Facet from the affected Products/Variants
    3. Return an ErrorResult which informs the user that the facet is used in channel products, and then also provide a "force" argument (like we do with the `deleteFacet` mutation currently) that would automatically remove the Facets as in 2 above.

Option 3 is the most complete handling, but would require some changes to the current gql schema to allow a union return type and then a bit more logic for the 2 modes. But the general outline of the implementation can be found in the [deleteFacet method source](https://github.com/vendure-ecommerce/vendure/blob/4900e1eab994b30cc953faa524503e2f0264f50a/packages/core/src/service/services/facet.service.ts#L175-L214).

2022-09-15 09:16 UTC, Izayda commented
And what do you think about adding facet/collection to channel? Full reindex? :)

2022-09-15 13:04 UTC, michaelbromley commented
Just adding a Facet to a channel should not need to change the search index (should it?). 

But adding a Collection will require not a full reindex but a running of the 'apply-collection-filters' queue for the added Collection. This would be done [here](https://github.com/vendure-ecommerce/vendure/blob/4a9ec5c87ad54351c5f48753f170846f9b912dc9/packages/core/src/service/services/collection.service.ts#L89) in the CollectionService - you can listen for the new `CollectionChannelEvent` and add a job to the queue with just that channel ID.

Removing a Collection will require reindex just for those ProductVariants which are part of the Collection.

2022-09-23 17:25 UTC, Izayda commented
Hi @michaelbromley!

I have switched branch from master to minor. Also have added some logic for affected variants/products.

Can you check this code? I'm not sure in using right ctx in every part of code and logic of affected items

2022-09-23 20:01 UTC, michaelbromley requested changes
See my comments. Thanks for the work on this so far - reviewing your changes allowed me to wrap my head around the problem fully for the first time. 

I think we're almost there - a few cleanups and the main change is with how to handle the removeFacetsFromChannel return type.

As I mentioned in the comment - I'm happy to collaborate on the last few details so let me know if you would like me to handle any of the remaining parts.

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/collection.service.ts
> +     * Assigns a Collections to the specified Channel
Should be "Assigns Collections" - no "a".

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/collection.service.ts
> +        const hasPermission = await this.roleService.userHasPermissionOnChannel(
I realized we also have to check the UpdateCollection permission. Background: I started off with just Catalog permission, that covers products, assets, collections, facets. Later I realized it needs to be more granular so created individual CRUD permissions for each entity. So now we need to consider both, and make sure User has permissions on at least 1 of them.

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/collection.service.ts
> +            Permission.UpdateCatalog,
Same thing with also checking UpdateCollection permission.

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/collection.service.ts
> +                return this.eventBus.publish(new CollectionChannelEvent(ctx, collection, input.channelId, 'assigned'));
I noticed that the `ChannelService.assignToChannels()` method publishes a generic `ChangeChannelEvent` which actually contains all the data of the new `CollectionChannelEvent`. I'm thinking that we can just rely on that event, rather than defining new events especially for Collection and Facet channel changes.

So why do we have a dedicated `AssetChannelEvent` and `ProductChannelEvent`? That's just because they were created _before_ the generic `ChangeChannelEvent`, which basically makes them obsolete but I needed to keep them so as to not create a breaking change.

So I'd suggest removing those 2 new custom events you defined. Less code is always nice!

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/collection.service.ts
> +            defaultChannel.id,
I think we should be keeping to the active channel, `ctx.channelId` rather than the default channel.

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/collection.service.ts
> +        ).then(clcs =>
I'd personally prefer the var to be named `collections` - this kind of abbreviation is not very clear IMO.

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +            Permission.UpdateCatalog,
See the comment I left on the CollectionService file - same applies here with the UpdateFacet permission.

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +     * Assigns a Facets to the specified Channel
Should be "Assigns Facets" without the "a"

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/collection.service.ts
> +     * Remove a Collections from the specified Channel
drop the "a" here too

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +        ).then(fcts =>
Name this `facets` - for 2 extra chars it's worth the improved readability!

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +     * Remove a Facets from the specified Channel
drop the "a"

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +            Permission.UpdateCatalog,
also add check for UpdateFacet permission

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +                } else if (input.force === undefined ? false : input.force) {
side note - this can be expressed as `if (input?.force)`

2022-09-23 20:01 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +    ): Promise<DeletionResponse[]> {
I see why you've decided to return an array of DeletionResponse, but I don't think we should do it this way. All the other `removeXFromChannel`mutations return an array containing the removed entities. We should attempt to stick as close to that as possible.

In this case I suggest you create a new ErrorResult:

```gql
type FacetInUseError implements ErrorResult {
    errorCode: ErrorCode!
    message: String!
    productCount: Int!
    variantCount: Int!
}
```

and then have the mutation return an array of either Facet or FacetInUseError as a new union type:

```gql
union RemoveFacetFromChannelResult = Facet | FacetInUseError

Mutation {
  removeFacetsFromChannel(input: RemoveFacetsFromChannelInput!): [RemoveFacetFromChannelResult!]!
}
```

This solution is getting rather advanced because now you also need to codegen the FacetInUseError TS class. Please let me know if you'd like my assistance with this part.

2022-09-23 20:04 UTC, Izayda commented on packages/core/src/service/services/collection.service.ts
> +                return this.eventBus.publish(new CollectionChannelEvent(ctx, collection, input.channelId, 'assigned'));
Ok, i also can mark that asset and product event are depreciated

2022-09-23 20:07 UTC, Izayda commented on packages/core/src/service/services/collection.service.ts
> +     * Assigns a Collections to the specified Channel
Thanks! I often make mistakes with "a" and "the"

2022-09-24 11:20 UTC, Izayda commented on packages/core/src/service/services/collection.service.ts
> +        const hasPermission = await this.roleService.userHasPermissionOnChannel(
But we already check this permission in resolver. Should we also check this permissions in resolver?

2022-09-24 11:33 UTC, Izayda commented on packages/core/src/service/services/collection.service.ts
> +        ).then(clcs =>
It shadows name of const defined above

2022-09-24 12:43 UTC, Izayda commented on packages/core/src/service/services/facet.service.ts
> +    ): Promise<DeletionResponse[]> {
I need some help here. I tried to implement, code is in current branch. But have some problems with typification

2022-09-26 08:07 UTC, michaelbromley commented on packages/core/src/service/services/facet.service.ts
> +    ): Promise<DeletionResponse[]> {
No problem. You've got it 90% there - I'll wrap the last bits up and try to get this merged today :)

2022-09-26 10:26 UTC, michaelbromley commented
Merged in https://github.com/vendure-ecommerce/vendure/commit/34840c943d5d57d1e652352d89196ceb5dc666f8

Thanks for your help on this! 🙏

2022-09-26 10:26 UTC, closed without merging