slide of image (carousel) added in the assets dialog admin-ui panel
vendure-ecommerce/vendure pull request #2370
Opened 2023-08-30 07:22 UTC by Mizan3050

implemented a generalize the solution to any place where we have a number of assets which can be opened in the dialog from:
product detail view
product variant detail view
collection detail view
asset list view

2023-09-04 12:12 UTC, michaelbromley commented
Hi! Just wanted to let you know I saw this and will properly review later this week.

2023-09-06 09:55 UTC, michaelbromley requested changes
Hi, this is a great PR, thanks so much. It really improves the UX!

I have a few small issues to fix, and then can you also make the PR against the `minor` branch rather than `master`, since it is a new feature and will go in the next minor release v2.1

2023-09-06 09:55 UTC, michaelbromley commented on packages/admin-ui/src/lib/core/src/shared/components/asset-preview-dialog/asset-preview-dialog.component.ts
> +    assets: AssetLike[];
Let's mark this as optional in case anyone already uses this component before this change, they won't be passing in the `locals: { assets }` array.

2023-09-06 09:55 UTC, michaelbromley commented on packages/admin-ui/src/lib/core/src/shared/components/asset-preview-dialog/asset-preview-dialog.component.ts
> +        this.assetsWithTags$ = of(this.assets);
Likewise this would then be changed to 

```ts
of(this.assets ?? [])
```

2023-09-06 09:55 UTC, michaelbromley commented on packages/admin-ui/src/lib/core/src/shared/components/asset-preview-dialog/asset-preview-dialog.component.ts
> +    assetsWithTags$;
This needs a type:

```ts
assetsWithTags$: Observable<Array<GetAssetQuery['asset']>>;
```

2023-09-06 09:55 UTC, michaelbromley commented on packages/admin-ui/src/lib/core/src/shared/components/asset-preview/asset-preview.component.ts
> +    @Input() assets: AssetLike[];
mark this as optional since existing external uses of the component will not be passing it.

```ts
@Input() assets?: AssetLike[];
```

2023-09-09 09:25 UTC, Mizan3050 commented
Hi!!
I have updated the PR with requested changes

2023-09-11 08:21 UTC, merged

2023-09-11 08:22 UTC, michaelbromley commented
Thanks for your help on this! 🙏  🥳