Enhance Stripe Plugin to Support Localized Order Confirmation Emails
vendure-ecommerce/vendure pull request #3298
Opened 2024-12-27 02:22 UTC by HerclasNido

# Description
This PR introduces updates to the Stripe Plugin to enable sending localized order confirmation emails based on the customer's language, rather than defaulting to English. Here's a summary of the changes:

- Added `languageCode` to Stripe Metadata: When creating a `paymentIntent`, the `languageCode` is now included in the `metadata` along with `channelToken`, `orderId`, and `orderCode`.
- Localized Context for Webhook Requests: When processing Stripe webhook requests at the /payments/stripe endpoint, the `createContext()` function now uses the `languageCode` from the metadata to set the context's language. This replaces the previous behavior of defaulting to `LanguageCode.en`.

These changes allow the `languageCode` passed during the `createStripePaymentIntent` mutation to be accessible in the `EmailTemplateLoader` for the "order-confirmation" event, ensuring emails are sent in the correct language.

# Breaking changes

No breaking change

# Checklist

📌 Always:
- [x] I have set a clear title
- [x] My PR is small and contains a single feature
- [x] I have [checked my own PR](## "Fix typo's and remove unused or commented out code")

👍 Most of the time:
- [ ] I have added or updated test cases
- [ ] I have updated the README if needed

_This is my first PR, so I’m not entirely sure if everything is correct. I’d appreciate any feedback to help me improve! 😊_

2024-12-27 02:26 UTC, HerclasNido commented
I have read the CLA Document and I hereby sign the CLA

2024-12-27 02:26 UTC, HerclasNido commented
recheck

2024-12-31 07:47 UTC, michaelbromley requested changes
Hi, thanks for this PR! It all looks good to me. The only thing I'd like you to change is to remove the package-lock.json file from the PR since I guess that should not have changed?

2025-01-09 09:26 UTC, michaelbromley approved these changes

2025-01-09 09:27 UTC, merged