chore(admin-ui): Add translation ru
vendure-ecommerce/vendure pull request #829
Opened 2021-04-18 20:33 UTC by XeL077

translate ru

2021-04-19 08:04 UTC, Izayda requested changes
Thank you for your PR! I have wrote some comments for pieces of translation that noticed.

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "assets-selected-count": "{ count } выбранные активы",
Выбрано объектов

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "dimensions": "Габаритные размеры",
Размеры (без слова габаритные)

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "add-asset": "Добавить медиа-объект",
Если использовать фразу "медиа-объект", то лучше его использовать во всех фразах перевода этого блока

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "focal-point": "Координаты",
Точка фокуса

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "notify-create-assets-success": "Created {count, plural, one {new Asset} other {{count} new Assets}}",
Тут перевод почему-то отсутсвует

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "original-asset-size": "Размер источника",
Тут идет речь о размере изображения в Kb, мб стоит как-то разделить разными словами dimensions и size?

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "set-focal-point": "Установить фокус",
Установить точку фокуса

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "unset-focal-point": "Не установлен",
Удалить точку фокуса

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "update-focal-point": "Точка обновления",
Обновить точку фокуса

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "update-focal-point-error": "Не удалось обновить координаты",
Не удалось обновить точку фокуса

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "update-focal-point-success": "Обновленная координата",
Точка фокуса была успешно обновлена

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "administrators": "Администратор",
Администраторы

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "dashboard": "Приборная панель",
Имхо, просто "Дашборд"

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "facets": "Facets",
Тут нет перевода, можно перевести как "Срезы" (Слово "фасет" тоже есть в русском языке, по сути синоним слову "срез")

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "roles": "Права",
Имхо, я бы оставил перевод как "Роли"

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "add-facet-value": "Add facet value",
Добавить значение среза

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "add-facets": "Add facets",
Добавить срез

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "assign-product-to-channel-success": "Продукт успешно назначен \"{ channel }\"",
Имхо, учитывая что такое канал, лучше везде использовать слово "добавить" вместо "назначить".

В данном случае, "Товар успешно добавлен в канал \"{ channel }\""

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "assign-products-to-channel": "Назначьте продукты каналу",
Добавить товары в канал

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "assign-to-channel": "Назначить каналу",
Добавить в канал

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "assign-variant-to-channel-success": "Вариант продукта успешно назначен для \"{ channel }\"",
Вариант товара успешно добавлен в канал

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "assign-variants-to-channel": "Назначьте варианты продукта каналу",
Добавить варианты товара в канал

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "assign-to-named-channel": "Назначить на { channelCode }",
Не совсем понимаю что означает данный лейбл

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "auto-update-option-variant-name": "Автоматически обновлять названия ProductVariants с помощью этой опции",
Автоматические обновлять название опций вариантов товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "auto-update-product-variant-name": "Automatically обновить имена ProductVariants",
Автоматические обновлять имена вариантов товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "channel-price-preview": "Предварительный просмотр цены канала",
Предварительный просмотр цен канала

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "confirm-adding-options-delete-default-body": "Добавление опций к этому продукту приведет к удалению существующего варианта по умолчанию. Вы хотите продолжить?",
Добавление опций к этому товару приведет к удалению существующего варианта товара по умолчанию. Вы хотите продолжить?

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "confirm-adding-options-delete-default-title": "Удалить вариант по умолчанию?",
вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "confirm-delete-facet": "Delete facet?",
Удалить срез?

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "confirm-delete-facet-value": "Delete facet value?",
Удалить значение среза?

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "confirm-delete-product-variant": "Удалить вариант продукта?",
вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "create-new-facet": "Create new facet",
Создать новый срез

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "default-variant": "Вариант по умолчанию",
Вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "delete-default-variant": "Удалить вариант по умолчанию",
вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "display-variant-cards": "Посмотреть детали",
Просмотр карточек вариантов

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "display-variant-table": "Показать в виде таблицы",
Просмотр в виде таблицы

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "facet-values": "Facet values",
Значения среза

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "no-featured-asset": "Нет рекомендованного медиа-объекта",
Выше использовалось слово "избранный" для featured-asset. Тут надо так же

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "no-selection": "Не выборано",
Опечатка. Не выбрано

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "notify-remove-product-from-channel-error": "Не удалось удалить продукт из канала",
Не удалось удалить товар из канала

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "notify-remove-product-from-channel-success": "Продукт успешно удален с канала",
Товар успешно удален из канала

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "notify-remove-variant-from-channel-error": "Не удалось удалить вариант продукта из канала",
Не удалось удалить вариант товара из канала

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "notify-remove-variant-from-channel-success": "Вариант продукта успешно удален из канала",
Вариант товара успешно удален из канала

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "out-of-stock-threshold": "Out-of-stock threshold",
Порог "нет в наличии"

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "out-of-stock-threshold-tooltip": "Sets the stock level at which this variant is considered to be out of stock. Using a negative value enables backorder support.",
Установите порог остатков на складе, после которого будет считаться, что варианта товара нет в наличии. При использовании отрицательного значения порога, включается поддержка предзаказа.

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "product-variants": "Вариает товара",
Вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "reindex-successful": "Indexed {count, plural, one {product variant} other {{count} product variants}} in {time}ms",
Проиндексировано. Нужен перевод всей строки

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "remove-from-channel": "Удалить с канала",
Удалить из канала

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "search-asset-name-or-tag": "Поиск по названию ресурса или тегам",
Выше было медиа-объект

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "search-for-term": "Искать термин",
Термин тут нельзя использовать. Просто "Искать по фразе"

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "search-product-name-or-code": "Поиск по названию продукта или коду",
товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "select-product": "Выбрать продукт",
Выбрать товар

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "select-product-variant": "Выберите вариант продукта",
Выберите вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "sku": "SKU",
Артикул

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "slug": "Slug",
Код

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "slug-pattern-error": "Slug is invalid",
Код задан неккоректно

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "stock-allocated": "Выделено",
Зарезервировано

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "stock-allocated-tooltip": "Количество единиц, выделенных для заказов, которые были проверены, но еще не выполнены",
Количество единиц, зарезервированных для заказов, которые были размещены, но еще не выполнены.

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "stock-on-hand": "Склад",
Количество на складе

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "stock-on-hand-tooltip": "Наличие на складе - количество физических единиц, имеющихся на складе.",
Количество на складе - количество физических единиц, имеющихся на складе.

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "stock-on-hand": "Склад",
Лучше наверное просто "На складе"

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "stock-saleable": "Продаваемый",
Доступно для продажи

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "stock-saleable-tooltip": "Количество продаваемых единиц, составляющих наличный запас, выделенной с учетом порогового значения отсутствия на складе",
Количество единиц, доступных для продажи с учетом порогового значения отсутствия на складе

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "tax-category": "Налоговая категория",
Категория налогов

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "track-inventory-tooltip": "При отслеживании, уровни запаса вариантов продукта будут автоматически корректироваться при продаже.",
вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "update-product-option": "Обновить вариант продукта",
вариант товара

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "remove-customers-from-group-success": "Removed {customerCount, plural, one {1 customer} other {{customerCount} customers}} from \"{ groupName }\"",
Нет перевода

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "province": "Провинция",
Регион

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "street-line-1": "Уличная линия 1",
Улица, строка 1

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "street-line-2": "Уличная линия 2",
Улица, строка 2

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "facets": "Facets",
Срезы

2021-04-19 08:04 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "create-fulfillment": "Создавайте удовлетворение",
Удолетворение?)

2021-04-19 08:04 UTC, merged

2021-04-19 08:06 UTC, michaelbromley commented
@Izayda I pushed the "merge" button just as your comments popped up in the GitHub UI!

If there are any refinements to be made, I'll accept another PR. I have no judgement on this so I'll let the experts decide what is correct!

2021-04-19 08:09 UTC, Izayda commented
Yeah, we made it at the same time) @XeL077 can we together improve some moments of translation? I have wrote some comments while morning coffee

2021-04-19 10:21 UTC, XeL077 commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "update-focal-point-error": "Не удалось обновить координаты",
This is "точка ф54+о"

2021-04-19 10:24 UTC, XeL077 commented
@Izayda, yes! I will improve translate and create new pull request.
Some lines I could not think of how to translate correctly.

I will run this version of the translation and do the validation using the context of use.

2021-04-19 10:24 UTC, Izayda commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "update-focal-point-error": "Не удалось обновить координаты",
Да, это сообщение появляется если не получается установить координаты точки фокуса.

![image](https://user-images.githubusercontent.com/8737418/115221596-8652f900-a112-11eb-99b5-92827c48f4b6.png)


Можно сделать что-то типа "Не удалось обновить координаты точки фокуса"

2021-04-19 10:25 UTC, XeL077 commented
@michaelbromley, will this translation already be available in the current master build version?

2021-04-19 10:27 UTC, Izayda commented
Thank you! You can write me before before creating PR and i can review your fork branch and if there will be some marks, i can made a PR to your fork to help you.

2021-04-19 10:38 UTC, michaelbromley commented
@XeL077 yes, the original PR you made has been merged into the master branch. Once you an Artem have made the necessary improvements I'll then merge the updated PR too. I plan to make a beta release in the next day or so, and these translations will be included in that release.

2021-04-19 23:28 UTC, XeL077 commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "original-asset-size": "Размер источника",
Изменить ключ "original-asset-size"?

2021-04-19 23:38 UTC, XeL077 commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "facets": "Facets",
Я не придумал хороший перевод для этого, не встречал на русском. Функционал похож на тэги или метки.

2021-04-20 00:17 UTC, XeL077 commented on packages/admin-ui/src/lib/static/i18n-messages/ru.json
> +    "create-fulfillment": "Создавайте удовлетворение",
"Создать выполнение?"
Какой тут контекст использования?

2021-04-20 21:32 UTC, XeL077 commented
@Izayda, hi! My fixes are here in the branch ->
https://github.com/XeL077/vendure/commit/1cf9d43c0d2ad75c930a1d3c0b659103c533f57f

Am I create pull request?
Maybe I forget some i18n messages lang keys. I will try to find and add them.

2021-04-21 04:20 UTC, Izayda commented
Hi! Great, thanks! I will look your branch today until evening

2021-04-22 10:19 UTC, Izayda commented
@XeL077 great job, really! Yeah, let's create PR. There are some small unimportant remarks, i will fix them in another PR next week