feat(elastic): add ability to customize index options and mappings
vendure-ecommerce/vendure pull request #996
Opened 2021-07-19 09:42 UTC by Izayda

Close #995

2021-07-20 09:04 UTC, michaelbromley requested changes
See comments in review - small changes.

Main issue I run into when testing this locally is that every other "reindex" call results in an error:

```json
{
  "name": "ResponseError",
  "meta": {
    "body": {
      "error": {
        "root_cause": [
          {
            "type": "illegal_argument_exception",
            "reason": "no write index is defined for alias [vendure-variants-reindex]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
          }
        ],
        "type": "illegal_argument_exception",
        "reason": "no write index is defined for alias [vendure-variants-reindex]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
      },
      "status": 400
    },
    "statusCode": 400,
    "headers": {
      "content-type": "application/json; charset=UTF-8",
      "content-length": "575"
    },
    "meta": {
      "context": null,
      "request": {
        "params": {
          "method": "POST",
          "path": "/_reindex",
          "body": "{\"source\":{\"index\":\"vendure-variants\"},\"dest\":{\"index\":\"vendure-variants-reindex\"}}",
          "querystring": "refresh=true",
          "headers": {
            "user-agent": "elasticsearch-js/7.11.0(win32 10.0.19042-x64; Node.js v16.2.0)",
            "x-elastic-client-meta": "es=7.11.0,js=16.2.0,t=7.11.0,hc=16.2.0",
            "content-type": "application/json",
            "content-length": "83"
          },
          "timeout": 30000
        },
        "options": {},
        "id": 17
      },
      "name": "elasticsearch-js",
      "connection": {
        "url": "http://localhost:9200/",
        "id": "http://localhost:9200/",
        "headers": {},
        "deadCount": 0,
        "resurrectTimeout": 0,
        "_openRequests": 0,
        "status": "alive",
        "roles": {
          "master": true,
          "data": true,
          "ingest": true,
          "ml": false
        }
      },
      "attempts": 0,
      "aborted": false
    }
  }
}
```

When this happens, it appears that the temporary timestamped indices do not get cleaned up:
![image](https://user-images.githubusercontent.com/6275952/126293681-4dbdd096-d48e-4771-9fd3-e7b563835c53.png)

2021-07-20 09:04 UTC, michaelbromley commented on packages/elasticsearch-plugin/src/elasticsearch.service.ts
> +                const existedIndexSettings = await this.client.indices.getSettings({ index });
I think "existing" is more grammatically correct than "existed" in this context.

2021-07-20 09:04 UTC, michaelbromley commented on packages/elasticsearch-plugin/src/elasticsearch.service.ts
> +                const temp_name = date.valueOf();
Is there a reason why some vars are snake_case? If not, it'd be better to keep the camelCase convention.

It is a little more idiomatic I think to use `getTime()` rather than `valueOf()`, though they both return the timestamp. You can also inline the `date` variable if it is not used anywhere else:

```
const tempName = new Date().getTime();
```

2021-07-20 09:04 UTC, michaelbromley commented on packages/elasticsearch-plugin/src/elasticsearch.service.ts
> +                    if (tempSettings[param]) delete tempSettings[param];
You don't need the `if` statements here. From MDN:

> If the property which you are trying to delete does not exist, delete will not have any effect and will return true.

2021-07-20 09:04 UTC, michaelbromley commented on packages/elasticsearch-plugin/src/elasticsearch.service.ts
> +                    Logger.warn(`Index "${index}" settings differ from index setting in vendure config! Consider to reindex data.`, loggerCtx);
Grammar: "Consider re-indexing the data"

2021-07-20 09:04 UTC, michaelbromley commented on packages/elasticsearch-plugin/src/elasticsearch.service.ts
> +                await this.client.indices.delete({ index: [`temp-` + `${temp_name}-${nameSalt}-products`, `temp-` + `${temp_name}-${nameSalt}-variants`] });
``` `temp-` + `${temp_name}-${nameSalt}-products` ``` is used 3 times here. Consider extracting into a function?

2021-07-20 11:59 UTC, Izayda commented
> See comments in review - small changes.
> 
> Main issue I run into when testing this locally is that every other "reindex" call results in an error:
> 
> ```json
> {
>   "name": "ResponseError",
>   "meta": {
>     "body": {
>       "error": {
>         "root_cause": [
>           {
>             "type": "illegal_argument_exception",
>             "reason": "no write index is defined for alias [vendure-variants-reindex]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
>           }
>         ],
>         "type": "illegal_argument_exception",
>         "reason": "no write index is defined for alias [vendure-variants-reindex]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"
>       },
>       "status": 400
>     },
>     "statusCode": 400,
>     "headers": {
>       "content-type": "application/json; charset=UTF-8",
>       "content-length": "575"
>     },
>     "meta": {
>       "context": null,
>       "request": {
>         "params": {
>           "method": "POST",
>           "path": "/_reindex",
>           "body": "{\"source\":{\"index\":\"vendure-variants\"},\"dest\":{\"index\":\"vendure-variants-reindex\"}}",
>           "querystring": "refresh=true",
>           "headers": {
>             "user-agent": "elasticsearch-js/7.11.0(win32 10.0.19042-x64; Node.js v16.2.0)",
>             "x-elastic-client-meta": "es=7.11.0,js=16.2.0,t=7.11.0,hc=16.2.0",
>             "content-type": "application/json",
>             "content-length": "83"
>           },
>           "timeout": 30000
>         },
>         "options": {},
>         "id": 17
>       },
>       "name": "elasticsearch-js",
>       "connection": {
>         "url": "http://localhost:9200/",
>         "id": "http://localhost:9200/",
>         "headers": {},
>         "deadCount": 0,
>         "resurrectTimeout": 0,
>         "_openRequests": 0,
>         "status": "alive",
>         "roles": {
>           "master": true,
>           "data": true,
>           "ingest": true,
>           "ml": false
>         }
>       },
>       "attempts": 0,
>       "aborted": false
>     }
>   }
> }
> ```
> 
> When this happens, it appears that the temporary timestamped indices do not get cleaned up:
> ![image](https://user-images.githubusercontent.com/6275952/126293681-4dbdd096-d48e-4771-9fd3-e7b563835c53.png)

I think this error appears because you have old indexes without aliases. 

Can you run two curl requests and send me results?
```
curl -X GET "localhost:9200/_cat/indices/?v=true&s=index&pretty"
curl -X GET "localhost:9200/_aliases?pretty"  
```

2021-07-20 12:01 UTC, Izayda commented
`no write index` means, that there multiple physical indices mapped to alias and elastic don't know which one to choose

2021-07-20 12:08 UTC, michaelbromley commented
```
$ curl -X GET "localhost:9200/_cat/indices/?v=true&s=index&pretty"
health status index                         uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   e2e-testsproducts             HdNegyP6TmOEbbEese6b3g   1   1         27          439    165.4kb        165.4kb
yellow open   e2e-testsvariants             R-73NtMyQUSbEYGXyDck4Q   1   1         37          905    215.7kb        215.7kb
yellow open   e2e-uuid-testsproducts        zfwJPv6MSpCc52ZVY9cuRQ   1   1         40           41    116.7kb        116.7kb
yellow open   e2e-uuid-testsvariants        8opAtx5vRpuYUcp17AkoRw   1   1         68           69    131.7kb        131.7kb
yellow open   vendure-products              CeQd5-S6Q768tffN0YjEjg   1   1         54           54     90.1kb         90.1kb
yellow open   vendure-products1626771597468 OcevSMNHT3eVclGV79_sqQ   1   1         54            0     85.5kb         85.5kb
yellow open   vendure-products1626771651315 dEUeLHN0SvOw9xmsOysNnw   1   1          0            0       230b           230b
yellow open   vendure-products1626771676223 Pagm1lzlRGKparI6Rf8Tog   1   1          0            0       230b           230b
yellow open   vendure-variants              w9ilM0oiRlqnChxe2pV-VQ   1   1         88           88      101kb          101kb
yellow open   vendure-variants1626771597468 75Yq0UwVR9WXXWxG3CLPAQ   1   1         88            0     93.2kb         93.2kb
yellow open   vendure-variants1626771651315 lHrZEzmgQqSI7WDHZ7Vwaw   1   1          0            0       230b           230b
yellow open   vendure-variants1626771676223 y9WWiWHCTIO7wWcHfebWKg   1   1          0            0       230b           230b
```

```
$ curl -X GET "localhost:9200/_aliases?pretty"
{
  "vendure-variants1626771651315" : {
    "aliases" : {
      "vendure-variants-reindex" : { }
    }
  },
  "vendure-products1626771676223" : {
    "aliases" : {
      "vendure-products-reindex" : { }
    }
  },
  "vendure-products1626771651315" : {
    "aliases" : {
      "vendure-products-reindex" : { }
    }
  },
  "vendure-products" : {
    "aliases" : { }
  },
  "vendure-variants" : {
    "aliases" : { }
  },
  "e2e-uuid-testsproducts" : {
    "aliases" : { }
  },
  "e2e-testsproducts" : {
    "aliases" : { }
  },
  "e2e-testsvariants" : {
    "aliases" : { }
  },
  "vendure-variants1626771676223" : {
    "aliases" : {
      "vendure-variants-reindex" : { }
    }
  },
  "vendure-products1626771597468" : {
    "aliases" : {
      "vendure-products-reindex" : { }
    }
  },
  "vendure-variants1626771597468" : {
    "aliases" : {
      "vendure-variants-reindex" : { }
    }
  },
  "e2e-uuid-testsvariants" : {
    "aliases" : { }
  }
}
```

2021-07-22 13:09 UTC, Izayda commented
Ok, this problem has appeared cause of original indices was a `physical` indices, not an aliases. 
Now reindex method is robust - original indices can now be `physical`, `deleted` or `alias`. Moreover, even if one of index is `corrupted`, method will fix it.

And clean up code

2021-07-23 07:59 UTC, merged

2021-07-23 08:01 UTC, michaelbromley commented
Thank you for all the work you put in on this!

Now that the index can be configured, it would be nice to include an example in the docs of what can be done. You mentioned you wanted to improve substring matching I think? If you have an example of the some config that can improve results, please share it and I'll add it as an example to the docs.

2021-07-23 08:04 UTC, Izayda commented
Ok, thanks, I will send examples tomorrow. Today we with my wife are in labor

2021-07-23 08:17 UTC, michaelbromley commented
No rush! There are more important things in life than code ;)

2021-07-26 13:45 UTC, Izayda commented
Two examples.

1. How to configure english stemmer and case independent search for `productName` field
```
indexSettings: {
                analysis: {
                    analyzer: {
                        custom_analyzer: {
                            tokenizer: 'standard',
                            filter: [
                                'lowercase',
                                'english_stemmer'
                            ]
                        }
                    },
                    filter : {
                        english_stemmer : {
                            type : 'stemmer',
                            name : 'english'
                        }
                    }
                }},
            indexMappingProperties: {
                productName: {
                    type: 'text',
                    analyzer:'custom_analyzer',
                    fields: {
                        keyword: {
                            type: 'keyword',
                            ignore_above: 256,
                        },
                    },

                }
            }
        }),
``` 
2. How to configure `max_result_window` index parameter to iterate over 10k items
```
indexSettings: { index: { max_result_window: 20000 },}
```

2021-07-26 13:48 UTC, Izayda commented
When you approximately plan to release new features? :)

2021-07-26 14:14 UTC, michaelbromley commented
I'll be releasing once I get through the planned v1.2 issues listed in the [roadmap](https://github.com/vendure-ecommerce/vendure/projects/3). I might not do _all_ of them, but I'd like to get most done. 

In any case the last minor release was on on 01/07, so I think the next minor should follow no more than 2 months later, potentially sooner.

2021-07-26 14:21 UTC, Izayda commented
Ok, then i probably can also to be in v1.2 with `facets` is shop-api.

Is there any easy way to make my own temporary version of elastic package? I should push it throw npm?

2021-07-28 15:31 UTC, michaelbromley commented
Yes you can publish to npm under a different package name, that would work fine.